version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/
      - ./config/:/etc/nginx/conf.d/
    networks:
      - net

#Docker Networks
networks:
  net:
    driver: bridge

