apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  volumes:
    - name: nfs-volume
      nfs:
        server: 10.254.0.9
        path: /mnt/share
  containers:
    - name: nginx
      image: levess007/nginx:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: "/var/www"
          name: nfs-volume
